### PR TITLE
Added native callback

### PR DESCRIPTION
**Pull request by AndreasMLarsen**
Added a callback passed in when calling _RequestAuthorizationTracking_. The callback is invoked when the request is completed or not available on the native side.

### CODE REVIEW

**Comment by TanGrumser** [comment]
For iOS devices with a version, that supports the ATT dialog the callback method isn't invoked after the dialog. For deviceces that do not support the dialog everything works fine.

**Comment by AndreasMLarsen** [comment]
@TanGrumser I just tested on a iPhone XS running iOS 14.5.1 and everything seems to work. I also tested in the xCode simulator with the same result. Do you have more information on the device that failed?

**Comment by TanGrumser** [comment]
@AndreasMLarsen You are right. I used [this script](https://github.com/TanGrumser/iOS_Support_PR_Test/blob/main/iOS_Support_PR_Test.cs) to test it again and everything worked perfectly. We trigger the ATT dialog when the user request a rewarded ad, but for some reason the ad will not show, when triggered in the callback method. I still haven't figured out why that is, but it has nothing to do with your implementation. I'm sorry for my accusation.
I thought the problem lies on the callback methods side, since the same code worked on devices with iOS version <14.5, but not on those with later versions, but i guess the ads SDK will not show ads, when the app doesn't have the focus (e.g. during the ATT dialog and seemingly when the callback method is invoked.)

**Comment by vita-unity** [comment]
been added to 1.2.0 release. Thanks!

**Pull request closed without merging**
